### ISSUE TITLE
Several issues with building the code

### ISSUE THREAD

**Issue by cryptogakusei** [arkworks-rs/poly-commit#109]
∂

## Summary of Bug

I tried following the directions provided in the README.md. On running `cargo build --release`, I am getting several issues, some of which are shown in the following image:
<img width="976" alt="Screenshot 2023-01-27 at 7 51 04 AM" src="https://user-images.githubusercontent.com/92956318/215129238-0f5286bc-e210-4afe-b2eb-75ef091b7dd3.png">

## Version

git commit hash is: 88c97d2ba60354fe6429500f99688038cb95cc4b

## Steps to Reproduce
My OS is MacOS Ventura 13.1.
My system is MacBook Air M2.

Clang --version:
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by mmagician** [comment]
poly-commit hasn't been fully migrated to version 0.4, like the dependent libraries have. Master branch isn't likely to work until the migration is complete. There's a branch called 'catch-up-algebra' where I had started the effort but it's not done yet. A PR to move that branch to 0.4 would be welcome though :)

**Comment by mmagician** [comment]
Completed now with the release of version 0.4.0.
