### ISSUE TITLE
Optimization for `open` for linear-code based PCS

### ISSUE THREAD

**Issue by mmagician** [arkworks-rs/poly-commit#128]
## Summary

The current interface doesn't allow room for certain optimizations to `open`.

## Problem Definition

Specifically, for linear code schemes such as Ligero, during `commit` we compute the merkle root, and to create the proof in `open` we again recompute the merkle tree to then send merkle proofs for a bunch of leaf indices. Ideally the `open` stage shouldn't need to recompute the tree.

## Proposal

We introduce a gap between the output of `commit` and the input to `check`.

Namely, `commit` would return an `ExtendedCommitment` (aka `PrivateCommitment`?) , and `verify` would only receive the `Committment`. We also introduce a trivial `into()` method that's a no-op in all current schemes, but for linear codes it sheds a few fields, such as the coefficients matrix, extended coefficients matrix and the merkle tree, saving the need to recompute them.

We can then leverage this new interface to further simplify the `commit` and `open` trait methods: instead of having a separate argument `rands`, we place the `rands` on the `ExtendedComittment`. Then the `into()` method would shed the `rands` field when converting it to be used in `check`.

@Antonio95 @autquis @Pratyush 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by Antonio95** [comment]
Yes! I would propose the name `CommitmentData` for the larger structure containing the commitment and auxiliary data (whether it be randomness, previously computed values, or anything else). This also makes it less likely to be thought of as an actual "commitment on steroids", which I could see happening with `ExtendedCommitment`.

**Comment by Pratyush** [comment]
Sounds like a good idea to have `commit` output the commitment and an additional "commitment state" (I presume that this is used in opening?). If so, a descriptive name would could be `CommitterState`?

**Comment by mmagician** [comment]
Correct, that would be used in `open`.

**Comment by Pratyush** [comment]
Hm then perhaps `CommitmentOpeningData` would be slightly better? (Because if I call commit in a sequence it's not like I'll be passing the state from one call to the next)

**Comment by mmagician** [comment]
Sure, we can start with that and see how the name feels once it's implemented :)

**Comment by autquis** [comment]
The question for the maintainers is, would you want all schemes in the repo to have the hiding property?

In #134 , we have added `PCCommitmentState` along with `PCRandomness`. Ideally, we should merge these two in one. One way to do so is to remove the methods from `PCRandomness`. This implies that we are not enforcing hiding property on the schemes of the repo. If a scheme is hiding, it implements these methods for its `Randomness`. However, if a scheme is not hiding, implementing these methods is unnecessary (e.g., #131 and #132).
