### ISSUE TITLE
`KZG10::open` and friends visibility

### ISSUE THREAD

**Issue by skaunov** [arkworks-rs/poly-commit#152]
## Summary

Streamline visibility in `mod kzg`: currently it offers entities which can be obtained only from other modules which is confusing.

## Problem Definition

`fn open...` are `pub(crate)` and it seems like it's the only way to get `Proof` in `kzg10`; of course, it is used in other modules, but it makes disentangling that thing quite confusing.

## Proposal

Either `pub` those functions from `kzg`, either `pub use` entities from `kzg` in modules where they can actually be obtained and `pub(crate)` them in `kzg`.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Pratyush** [comment]
Thanks for noticing this papercut! Making the methods `pub` would be fine; would you like to make a PR?

**Comment by skaunov** [comment]
Yep! Just wasn't sure which path was better, now that's clear.
