### ISSUE TITLE
Okay to commit a degree-0 polynomials?

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/poly-commit#40]
When we are writing tests, we want to forge a trivial circuit with a specific number of constraints and nonzero entries, though the circuit itself is trivial (we may just write the same LC a million times).

This, however, would fail. A trivial constraint system may cause A, B, C matrices in Marlin to be too simple, such as after "row", "col" computation, the "val" polynomial could become a degree-zero polynomial.

Poly-commit, specifically KZG10 implementation, for some reasons, refuses to commit a degree-zero polynomial (during `commit` and `open`).

```
Error::check_degree_is_within_bounds(polynomial.degree(), powers.size())?;
```
which,
```
    pub(crate) fn check_degree_is_within_bounds(
        num_coefficients: usize,
        num_powers: usize,
    ) -> Result<(), Self> {
        if num_coefficients < 1 {
            Err(Error::DegreeIsZero)
        } else {
            Self::check_degree_is_too_large(num_coefficients, num_powers)
        }
    }
```

----------------

Reading KZG10, it seems not obvious that degree-zero polynomial cannot be committed? I guess you can commit a degree-zero polynomial (which is a constant)?

Should we remove this restriction?

**Comment by swasilyev** [comment]
In KZG an openning proof to the committed degree N polynomial is a commitment to a degree N-1 quotient polynomial. Doesn't make much sense for N = 0, but sure you can commit to a constant c with cG.

**Comment by weikengchen** [comment]
Yes.

And there seems to be a way for one to open it, though the witness now becomes `1_{G}` (the identity in the group), and the verification becomes trivially checking `e(g, g)^c = e(C, g)` where `C` is the commitment `g^c`, where `c` is the constant.

**Comment by weikengchen** [comment]
and in this case, g^{\alpha} is basically never used.
