### ISSUE TITLE
`KZG10` does not implement `PolynomialCommitment`

### ISSUE THREAD

**Issue by bhgomes** [arkworks-rs/poly-commit#86]
## Summary of Bug

The `KZG10` struct which implements a polynomial commitment scheme on its own does not implement the `PolynomialCommitment` trait. Either it should be implemented and/or the trait itself should be simplified to make this implementation easier.

## Version

latest commit: cafc05e39692bbc5c383990063ad851f0b94a553

**Comment by Pratyush** [comment]
It indeed does not, as the core KZG construction doesn't show how to do batching, or to implement strict degree bounds. I recommend using either `MarlinKZG10` or `SonicKZG10`, which do implement the `PolynomialCommitment` trait

**Comment by bhgomes** [comment]
I see, thanks!
