### ISSUE TITLE
Fix and update dependencies to 0.3

### ISSUE THREAD

**Issue by vlopes11** [arkworks-rs/poly-commit#92]
## Summary

Latest version is not building. We should target published crates instead of github branches so we can publish a new version for this crate

## Problem Definition

Unpublished branches are harder to manage and keep track of semver/latest updates

## Proposal

Fix minor issues and prepare to release

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by huitseeker** [comment]
@Pratyush This seems to have been closed by https://github.com/arkworks-rs/poly-commit/pull/93

**Comment by mmagician** [comment]
@huitseeker yes now we should target 0.4. 
There's a branch called "catch-up-algebra" that's WIP to get there.
